// Code generated by scripts/gen_cli_contracts.py from scripts/build_images.py; DO NOT EDIT.
//
// scripts/build_images.py is the single source of this table (R3). Edit it there,
// then run `python scripts/gen_cli_contracts.py`; T1 fails until the two agree.

package doctor

// StepImages is every step image the local executor resolves, as
// `<name>:<tag>`, in the IMAGES table's dependency order (a parent always
// precedes its children). `lazyaf doctor` reports each one missing locally
// with the pull-and-retag remedy; nothing here is ever pulled by doctor.
var StepImages = []string{
	"lazyaf-base:dev",
	"lazyaf-debug-sidecar:dev",
	"lazyaf-agent-base:dev",
	"lazyaf-claude:dev",
	"lazyaf-gemini:dev",
	"lazyaf-test-runner:dev",
}
