"""add_workspaces_table

Revision ID: 9495b26aec48
Revises: 5b8e88c7c2ce
Create Date: 2026-01-03 16:39:28.733276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9495b26aec48'
down_revision: Union[str, Sequence[str], None] = '5b8e88c7c2ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspaces',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('pipeline_run_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('use_count', sa.Integer(), nullable=False),
    sa.Column('volume_name', sa.String(length=64), nullable=False),
    sa.Column('repo_id', sa.String(length=36), nullable=False),
    sa.Column('branch', sa.String(length=255), nullable=True),
    sa.Column('commit_sha', sa.String(length=40), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('state_history', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(), nullable=False),
    sa.Column('cleaned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], ),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workspaces_pipeline_run_id'), ['pipeline_run_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workspaces_pipeline_run_id'))

    op.drop_table('workspaces')
    # ### end Alembic commands ###
