#!/usr/bin/env python3
"""
Build the LazyAF step images (Phase 12.3, agent tree added in 12.5).

Usage:
    python scripts/build_images.py            # build stale/missing images
    python scripts/build_images.py --force    # rebuild everything
    python scripts/build_images.py --check    # exit 1 listing stale/missing,
                                              # build nothing

Tag scheme: lazyaf-base:dev, lazyaf-agent-base:dev, lazyaf-claude:dev,
lazyaf-gemini:dev, lazyaf-test-runner:dev. `:dev` is the moving local tag
every reference uses — NO `:latest` anywhere (grep-able rule). Each build
stamps `LABEL lazyaf.content-hash=<sha256[:12]>` of the image's build context
tree; a build is SKIPPED when the local `:dev` image already carries the
computed hash.

PARENT-HASH CHAIN (12.5: multi-level). Every image names its parent SUBDIR,
and its content hash folds the parent's hash in, so a base change makes
grandchildren stale too:

    base ─┬─ agent-base ─┬─ claude
          │              └─ gemini
          └─ test-runner

STAGED BUILD CONTEXT (12.5). lazyaf-agent-base installs runner-common, which
lives at REPO_ROOT/runner-common and must NOT be vendored under images/ (a
second copy of the executors in git is exactly the R3 violation 12.5 exists
to remove) and must NOT be bind-mounted (images must be self-contained for
12.6 remote nodes). So each image is built from a TEMPORARY staged context:
its own images/<subdir>/ tree, plus each declared extra source copied in
under a fixed name, minus STAGE_EXCLUDE. Two consequences that matter:

- the content hash is computed over the STAGED tree, so runner-common's
  sources are hash inputs of lazyaf-agent-base (edit an executor -> the
  agent images go stale), and
- STAGE_EXCLUDE keeps build-irrelevant churn (test edits, lockfile bumps,
  caches, virtualenvs) OUT of both the context and the hash, so editing
  runner-common/tests/** can never force an agent-image rebuild.

A pre-built wheel checked into images/ was rejected for the same reason:
wheels are not byte-reproducible, so the hash would churn on every build and
`--check` would always report stale.

Step images are deliberately NOT compose services and are never auto-built by
the backend: LocalExecutor fails a step loudly with "Image not found:
lazyaf-base:dev" — that message plus `--check` is the rebuild trigger story.

Pure docker SDK (mirrors workspace/population.py's client handling) — no
shelling out, Windows-host friendly.
"""
import argparse
import hashlib
import shutil
import sys
import tempfile
from pathlib import Path

# Docker build output contains non-cp1252 characters; never let a Windows
# console encoding crash the build script.
for _stream in (sys.stdout, sys.stderr):
    if hasattr(_stream, "reconfigure"):
        _stream.reconfigure(errors="replace")

REPO_ROOT = Path(__file__).resolve().parent.parent
IMAGES_ROOT = REPO_ROOT / "images"

TAG = "dev"
HASH_LABEL = "lazyaf.content-hash"

# (subdir under images/, image name, parent subdir | None, extra_context)
# in dependency order: a parent always precedes its children.
# extra_context entries are (absolute source path, name inside the context).
IMAGES = [
    ("base",        "lazyaf-base",        None,        []),
    ("agent-base",  "lazyaf-agent-base",  "base",      [(REPO_ROOT / "runner-common", "runner-common")]),
    ("claude",      "lazyaf-claude",      "agent-base", []),
    ("gemini",      "lazyaf-gemini",      "agent-base", []),
    ("test-runner", "lazyaf-test-runner", "base",      []),
]

# Path components dropped when staging a build context. Everything here is
# build-irrelevant by construction; keeping it out of the STAGED tree keeps
# it out of the content hash as well, which is the whole point (editing
# runner-common/tests must not restamp lazyaf-agent-base).
#   __pycache__/*.pyc : host bytecode, already skipped by tree_hash
#   *.egg-info, dist  : local build residue, regenerated by the pip install
#   .venv             : a multi-hundred-MB host virtualenv, never installable
#   uv.lock           : a dev lockfile the image install does not consult
#   tests             : the package's own suite, not shipped by
#                       [tool.setuptools.packages.find] anyway
#   .pytest_cache /   : tool caches whose CONTENT changes every time the
#   .mypy_cache /       runner-common suite runs (v/cache/lastfailed etc.).
#   .ruff_cache /       Not in the 12.5 design's literal list, added because
#   .coverage /         without them a green test run would restamp
#   htmlcov             lazyaf-agent-base — the exact churn STAGE_EXCLUDE
#                       exists to prevent.
STAGE_EXCLUDE = (
    "__pycache__",
    ".egg-info",
    "dist",
    ".venv",
    "uv.lock",
    "tests",
    ".pytest_cache",
    ".mypy_cache",
    ".ruff_cache",
    ".coverage",
    "htmlcov",
)


def _is_excluded(relative: Path) -> bool:
    """True when any component of ``relative`` matches STAGE_EXCLUDE.

    ``.egg-info`` matches as a SUFFIX (the directory is named
    ``runner_common.egg-info``); every other token matches a whole
    component, so a legitimate file called ``distributed.py`` survives while
    a ``dist/`` directory does not.
    """
    for part in relative.parts:
        for token in STAGE_EXCLUDE:
            if part == token or (token.startswith(".") and part.endswith(token)):
                return True
        if part.endswith(".pyc"):
            return True
    return False


def _copy_tree(source: Path, destination: Path) -> None:
    """Copy ``source`` into ``destination`` honoring STAGE_EXCLUDE."""
    for path in source.rglob("*"):
        relative = path.relative_to(source)
        if _is_excluded(relative):
            continue
        target = destination / relative
        if path.is_dir():
            target.mkdir(parents=True, exist_ok=True)
        else:
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(path, target)


def stage_context(image_dir: Path, extras=()) -> Path:
    """Copy image_dir/* plus each extra source into a fresh temp dir.

    Returns the staged directory; the CALLER removes it (in a finally). The
    staged tree is both what docker builds and what tree_hash hashes, so the
    content-hash label can never describe a context the build did not see.
    """
    staged = Path(tempfile.mkdtemp(prefix="lazyaf-ctx-"))
    _copy_tree(image_dir, staged)
    for source, name in extras:
        if not source.exists():
            raise FileNotFoundError(
                f"staged context source missing: {source} (wanted as '{name}' "
                f"in the {image_dir.name} build context)"
            )
        _copy_tree(source, staged / name)
    return staged


def tree_hash(directory: Path, extra: str = "") -> str:
    """sha256[:12] over the directory tree (sorted relative paths + bytes).

    `extra` folds a parent image's hash into a child's, so children go stale
    when the base changes even if their own directory did not.
    """
    h = hashlib.sha256()
    h.update(extra.encode())
    # Sort by the normalized POSIX relative path, NOT the native Path: on
    # Windows the raw sort key contains backslashes (0x5C) which collate
    # differently from '/' (0x2F) against dots and letters, so the same tree
    # hashed in a different order on host vs container (dogfood run #8: host
    # label 723a51a4 vs in-container 115b6472 for identical content).
    entries = sorted(
        (p for p in directory.rglob("*") if not p.is_dir() and "__pycache__" not in p.parts),
        key=lambda p: str(p.relative_to(directory)).replace("\\", "/"),
    )
    for path in entries:
        h.update(str(path.relative_to(directory)).replace("\\", "/").encode())
        h.update(b"\0")
        # Normalize line endings so a CRLF checkout hashes like LF
        h.update(path.read_bytes().replace(b"\r\n", b"\n"))
        h.update(b"\0")
    return h.hexdigest()[:12]


def local_hash(client, image_ref: str):
    """Return the content-hash label of the local image, or None if absent."""
    import docker

    try:
        return client.images.get(image_ref).labels.get(HASH_LABEL)
    except docker.errors.ImageNotFound:
        return None


def build_image(client, directory: Path, image_ref: str, content_hash: str) -> None:
    """Build one image, streaming build output; raise on failure."""
    from docker.errors import BuildError

    print(f"[build] {image_ref}  (hash {content_hash})  <- {directory}")
    try:
        _, logs = client.images.build(
            path=str(directory),
            tag=image_ref,
            buildargs={"CONTENT_HASH": content_hash},
            rm=True,
        )
        for chunk in logs:
            line = chunk.get("stream")
            if line and line.strip():
                print(f"    {line.rstrip()}")
    except BuildError as e:
        for chunk in e.build_log:
            line = chunk.get("stream") or chunk.get("error")
            if line and str(line).strip():
                print(f"    {str(line).rstrip()}", file=sys.stderr)
        raise


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--force", action="store_true", help="rebuild even if fresh")
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit nonzero listing missing/stale images without building",
    )
    args = parser.parse_args()

    try:
        import docker
    except ImportError:
        print("docker SDK not installed (pip install docker)", file=sys.stderr)
        return 2

    try:
        client = docker.from_env()
        client.ping()
    except Exception as e:
        print(f"Docker daemon not reachable: {e}", file=sys.stderr)
        return 2

    # subdir -> content hash, so a child folds its PARENT's hash in and a
    # grandchild transitively folds the base's. IMAGES is in dependency
    # order, so a parent's entry always exists by the time a child reads it.
    hashes: dict = {}
    stale = []
    built = 0
    for subdir, name, parent, extras in IMAGES:
        directory = IMAGES_ROOT / subdir
        image_ref = f"{name}:{TAG}"

        # Stage (and hash) even under --check: the hash must be computed over
        # exactly the tree a build would see, or --check and the build would
        # disagree about staleness.
        staged = stage_context(directory, extras)
        try:
            content_hash = tree_hash(staged, extra=hashes[parent] if parent else "")
            hashes[subdir] = content_hash

            current = local_hash(client, image_ref)
            if current == content_hash and not args.force:
                print(f"[fresh] {image_ref}  (hash {content_hash})")
                continue

            state = "missing" if current is None else f"stale (has {current})"
            if args.check:
                stale.append(f"{image_ref}: {state}, want {content_hash}")
                continue

            # Name the SOURCE directory here: build_image only ever sees the
            # staged temp path, which tells a human nothing.
            print(f"[stale] {image_ref}: {state}  <- images/{subdir}")
            build_image(client, staged, image_ref, content_hash)
            built += 1
        finally:
            shutil.rmtree(staged, ignore_errors=True)

    if args.check:
        if stale:
            print("Missing/stale step images (run: python scripts/build_images.py):")
            for line in stale:
                print(f"  {line}")
            return 1
        print("All step images fresh.")
        return 0

    print(f"[done] {built} image(s) built.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
