// Code generated by scripts/gen_cli_contracts.py from backend/app/config.py; DO NOT EDIT.
//
// backend/app/config.py is the single source of this table (R3). Edit it there,
// then run `python scripts/gen_cli_contracts.py`; T1 fails until the two agree.

package envfile

// PlaceholderSecrets are the "I copied the template and did not fill it in"
// shapes the backend refuses at startup (config.py's _PLACEHOLDER_SECRETS),
// sorted. Compared case-insensitively against a trimmed value, exactly as
// the backend does; `lazyaf init` replaces one, `lazyaf doctor` fails on one.
var PlaceholderSecrets = []string{
	"<generate>",
	"change-in-production",
	"change-me",
	"change_me",
	"changeme",
	"generate-me",
	"generateme",
	"none",
	"null",
	"placeholder",
	"replace-me",
	"replaceme",
	"secret",
	"tbd",
	"todo",
	"unset",
	"your-secret-here",
}

// RetiredPublicSecrets are the constants LazyAF used to ship as defaults.
// They are public (git history, image layers, every fork), so a .env still
// holding one is treated as unset - exactly as the backend treats it
// (config.py's RETIRED_PUBLIC_SECRETS). Compared exactly, not lowercased.
var RetiredPublicSecrets = []string{
	"lazyaf-runner-auth-secret-key-change-in-production",
	"lazyaf-step-auth-secret-key-change-in-production",
}
