package envfile

import "strings"

// ActionKind is what Plan decided for one managed key.
type ActionKind string

const (
	Generated ActionKind = "generated"
	Kept      ActionKind = "kept"
	Delegated ActionKind = "delegated"
)

// Action is one managed key and what happened to it.
type Action struct {
	Key  string
	Kind ActionKind
}

// GeneratedHeader opens the block Plan appends for keys the file lacked.
const GeneratedHeader = "# --- generated by lazyaf init ---------------------------------------"

// Plan is one pass over the managed keys: the document to write and what
// was decided per key (bootstrap_secrets.py:212-267).
//
// Pure apart from the random source: no file I/O. That is what makes the
// concurrency story testable - the caller does read, plan, atomic-write, all
// inside the lock. getenv is the ambient environment (a *_FILE exported in
// the shell delegates exactly as one in the file does).
func Plan(lines []string, getenv func(string) string) ([]Line, []Action, error) {
	values := ReadValues(lines)
	doc := make([]Line, 0, len(lines)+8)
	for _, l := range lines {
		doc = append(doc, Verbatim(l))
	}
	var actions []Action
	var appended []Line

	for _, managed := range ManagedSecrets {
		fileVar := managed.Key + "_FILE"
		// A *_FILE pointer is an explicit statement about where the secret
		// lives. Generating an inline value next to it would write a secret
		// that is silently shadowed at resolution time.
		if strings.TrimSpace(values[fileVar]) != "" || strings.TrimSpace(getenv(fileVar)) != "" {
			actions = append(actions, Action{managed.Key, Delegated})
			continue
		}
		current, present := values[managed.Key]
		if present && !IsPlaceholder(current) {
			actions = append(actions, Action{managed.Key, Kept})
			continue
		}

		secret, err := GenerateSecret()
		if err != nil {
			return nil, nil, err
		}
		// Replace an existing empty/placeholder assignment where it stands,
		// so the operator's own ordering and comments survive. The LAST
		// active assignment is the one dotenv honours, so that is the one
		// replaced (bootstrap_secrets.py:241-246).
		replaced := false
		for i := len(doc) - 1; i >= 0; i-- {
			if key, _, ok := SplitAssignment(doc[i].Text); ok && key == managed.Key {
				doc[i] = Assignment(managed.Key, secret)
				replaced = true
				break
			}
		}
		if !replaced {
			appended = append(appended,
				Verbatim("# "+managed.Purpose),
				Assignment(managed.Key, secret))
		}
		actions = append(actions, Action{managed.Key, Generated})
	}

	if len(appended) > 0 {
		// A separating blank line unless the file already ends in one. A
		// just-replaced assignment has empty Text but is not blank.
		if last := len(doc) - 1; last >= 0 && (!doc[last].Secret.IsZero() || strings.TrimSpace(doc[last].Text) != "") {
			doc = append(doc, Verbatim(""))
		}
		doc = append(doc,
			Verbatim(GeneratedHeader),
			Verbatim("# Random per-installation values. Keep them; rotating one invalidates"),
			Verbatim("# in-flight step tokens and disconnects runner agents until they match."))
		doc = append(doc, appended...)
	}
	return doc, actions, nil
}
